name: build
on:
  push:
  pull_request:
jobs:
  test:
    name: ${{ matrix.os }} test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
        include:
          # focal
          - os: ubuntu-20.04
    steps:
      # Checkout this repository.
      - uses: actions/checkout@v2
      # Checkout the checkmake repository to build.
      - name: Checkout checkmake
        uses: actions/checkout@v2
        with:
          repository: mrtazz/checkmake
          path: vendor/checkmake
      - name: Build checkmake
        run: docker build --build-arg BUILDER_NAME='Jun Aruga' --build-arg BUILDER_EMAIL='jun.aruga@gmail.com' -t checkmake vendor/checkmake
      # Test in test_make directory.
      - name: Run checkmake
        run: docker run -v "$PWD/Makefile":/Makefile checkmake
        working-directory: ./test_make
      - run: make
        working-directory: ./test_make
      - run: make test
        working-directory: ./test_make
      # Test in test_automake directory.
      - run: autoreconf -i
        working-directory: ./test_automake
      - run: ./configure
        working-directory: ./test_automake
      - run: make
        working-directory: ./test_automake
